Backport of https://github.com/Unity-Technologies/Graphics/pull/7025
Bonus : Including changes from https://github.cds.internal.unity3d.com/unity/vfx-graphics/pull/295 (cc @gabriel-delacruz)

commit c7ed2f685ab3fe9c93d893f82ae571e105d47d60
Author: Paul Demeulenaere <pauld@unity3d.com>
Date:   Mon Feb 21 15:38:13 2022 +0100

    Update changelog.md

commit 351ec2a9ebe477a15bda3f7d7a8d33670cf548d0
Author: Paul Demeulenaere <pauld@unity3d.com>
Date:   Mon Feb 21 15:13:10 2022 +0100

    Fix OGL in Standalone

    - "opengl" corresponds to "kShaderCompPlatformGL_Obsolete" (GL2+)
    - "glcore" is "kShaderCompPlatformOpenGLCore" (GL 3+ supports compute)

    I don't explain why it sometimes works in editor or sometimes completly silent.  ¯¯\_(ヅ)_/¯¯

    See https://github.cds.internal.unity3d.com/unity/unity/blob/8d5d36f123d953029e8bf8f982576aa6a0696a2d/Tools/UnityShaderCompiler/ShaderCompilerClient.h#L35
    See also special alias declaration https://github.cds.internal.unity3d.com/unity/unity/blob/5a8e0e752a3977687cd273e5692567e834e3f27b/Tools/UnityShaderCompiler/Utilities/ShaderImportUtils.cpp#L51

    Fix case https://fogbugz.unity3d.com/f/cases/1403988/

commit 734850da9b4cb70800e6b9ad5f574ada1000291f
Merge: a700c33af20 778ddac6207
Author: Paul Demeulenaere <pauld@unity3d.com>
Date:   Mon Feb 21 09:19:44 2022 +0100

    Merge branch 'master' into vfx/fix/1392834-remove-invalid-vfx-passes-from-sg

commit a700c33af20ab9a12e7aa77fb2de529d8474c9cf
Author: Paul Demeulenaere <pauld@unity3d.com>
Date:   Thu Feb 17 17:01:26 2022 +0100

    *Apply formatting

commit bfd7d6ccb64951734a2540e009dd45cce87e9698
Author: Paul Demeulenaere <pauld@unity3d.com>
Date:   Thu Feb 17 16:52:05 2022 +0100

    kPragmaDescriptorNone isn't null

    Simpler to avoid multiple search for replacement
    Resolve issue https://github.com/Unity-Technologies/Graphics/pull/7025#discussion_r804681478

commit 350e4aa9ca47a4ca73141a0d86c33f8079cbb906
Author: Paul Demeulenaere <pauld@unity3d.com>
Date:   Thu Feb 17 12:01:07 2022 +0100

    *Add correct support of #pragma require cubearray

    Several cases where needed
    - Compute (and implicit compute like sorting)
    - Builtin Output
    - SG Output

commit 882bdb7476c05c179b12cffe3331ea531f60705a
Author: Paul Demeulenaere <pauld@unity3d.com>
Date:   Thu Feb 17 10:12:18 2022 +0100

    Correct implementation VFXCommon.hlsl

    TODO: Add needed pragma dynamically https://unity.slack.com/archives/C02TGPN8MRV/p1644932447721759?thread_ts=1644242387.827459&cid=C02TGPN8MRV

commit 4bb5caccd282e75c16b0f29a873e6f704e1b257e
Merge: da0454ce4fe a4b081aebd4
Author: Paul Demeulenaere <pauld@unity3d.com>
Date:   Thu Feb 17 09:52:47 2022 +0100

    Merge branch 'master' into vfx/fix/1392834-remove-invalid-vfx-passes-from-sg

    # Conflicts:
    #	com.unity.visualeffectgraph/CHANGELOG.md

commit da0454ce4fe43004c2e02259bf559b6bfa1984f0
Author: Paul Demeulenaere <pauld@unity3d.com>
Date:   Thu Feb 17 09:52:10 2022 +0100

    Revert "Workaround"

    This reverts commit 6a702852b7418eed2a943f858b9e8f1223a472cd.

commit 6a702852b7418eed2a943f858b9e8f1223a472cd
Author: Paul Demeulenaere <pauld@unity3d.com>
Date:   Fri Feb 11 09:28:49 2022 +0100

    Workaround

    Issue introduced at https://github.com/Unity-Technologies/Graphics/pull/2346
    See this conversation

commit ca0371de307e0c85ccb8b85100640f7eddb56328
Author: Gregory Mitrano <gregory.mitrano@unity3d.com>
Date:   Wed Feb 9 08:19:20 2022 -0500

    Fix Regression in GLCore from GH #7029

    The changes in GH #7029 accidentally broke the platform shader macro
    override system for GLCore's texture cube arrays. This change fixes
    the issue by restoring the missing platform macros.

commit 3683c8730e03d009b463abf03dc1e328fb05bfb5
Author: Paul Demeulenaere <pauld@unity3d.com>
Date:   Tue Feb 8 18:28:45 2022 +0100

    Revert unexpected merge change

commit dbf296428f8cad5f5aa5fb7963741dd0bcbbdf95
Merge: 3032c86e1e3 f70620ae8d6
Author: Paul Demeulenaere <pauld@unity3d.com>
Date:   Tue Feb 8 18:03:15 2022 +0100

    Merge branch 'master' into vfx/fix/1392834-remove-invalid-vfx-passes-from-sg

commit 3032c86e1e3fd0e4ddad3658e765a1ab5fbd3f3c
Author: Paul Demeulenaere <pauld@unity3d.com>
Date:   Mon Feb 7 16:44:26 2022 +0100

    *Update changelog.md

commit 033b409681c8176738f9b48047a132d40692365d
Author: Paul Demeulenaere <pauld@unity3d.com>
Date:   Mon Feb 7 16:40:32 2022 +0100

    *Update comment

    To anticipate incoming change with GetInstancingAdditionalDefines

commit 4f88add526b17db8323f1642eedb48a661bfe709
Author: Paul Demeulenaere <pauld@unity3d.com>
Date:   Mon Feb 7 16:31:32 2022 +0100

    Add OpenGL in target

    Early detecting VFX compilation error

commit f4513a7425ecf904eb037c79db3e4885a8ef1db1
Author: Paul Demeulenaere <pauld@unity3d.com>
Date:   Mon Feb 7 16:22:06 2022 +0100

    Fix build of GLCore.hlsl

    Fix failure com.unity.render-pipelines.core/ShaderLibrary/Texture.hlsl(66)
    https://github.com/Unity-Technologies/Graphics/blob/65776aefaaa7f24455cc4b5fa8b3b90c8dd606b7/com.unity.render-pipelines.core/ShaderLibrary/Texture.hlsl#L66

commit 7fed326975f7be20d7a32af2131f4be99c55fe56
Author: Paul Demeulenaere <pauld@unity3d.com>
Date:   Mon Feb 7 16:03:44 2022 +0100

    Same instancing option removal in HDRP

commit 16fae6cbdf37ebf830496f6dc32aee05e69dd144
Author: Paul Demeulenaere <pauld@unity3d.com>
Date:   Mon Feb 7 15:56:37 2022 +0100

    Removing pass was wrong, replace pragma

    Some needed pass uses the default target 2.0 on URP and it can be problematic to change the pass count
    Bonus : add a mechanism to remove useless instancing multicompile

commit 9789e9966aa68b66227dad341cab6c2be3a26dce
Author: Paul Demeulenaere <pauld@unity3d.com>
Date:   Fri Feb 4 17:19:30 2022 +0100

    Statify kInvalidPassWithPragmas

commit c26c54bcfadd3ee900d175574727a56dd3c3c13e
Merge: e348f545a0c 5850cf7cfe2
Author: Paul Demeulenaere <pauld@unity3d.com>
Date:   Fri Feb 4 16:56:57 2022 +0100

    Merge branch 'master' into vfx/fix/1392834-remove-invalid-vfx-passes-from-sg

commit e348f545a0c75a8123ebf43d2c7f6f2a3352f37f
Author: Paul Demeulenaere <pauld@unity3d.com>
Date:   Tue Feb 1 17:37:43 2022 +0100

    Draft removing target 2.0

    See https://fogbugz.unity3d.com/f/cases/1392834/
    See also this conversation https://unity.slack.com/archives/G1BTWN88Z/p1643362523117700

# Conflicts:
#	com.unity.visualeffectgraph/CHANGELOG.md
#	com.unity.visualeffectgraph/Shaders/SDFBaker/GenSdfRayMap.compute
#	com.unity.visualeffectgraph/Shaders/Sort.compute
#	com.unity.visualeffectgraph/Shaders/UpdateStrips.compute
#	com.unity.visualeffectgraph/Shaders/VFXCameraSort.template
#	com.unity.visualeffectgraph/Shaders/VFXCopyBuffer.compute
#	com.unity.visualeffectgraph/Shaders/VFXFillIndirectArgs.compute
#	com.unity.visualeffectgraph/Shaders/VFXInit.template
#	com.unity.visualeffectgraph/Shaders/VFXOutputUpdate.template
#	com.unity.visualeffectgraph/Shaders/VFXUpdate.template