[2022.3][QNX] Fix non XR platform compile
Backport of https://github.cds.internal.unity3d.com/unity/unity/commit/720d3219c91d69e442a8c32a86e5497dc362c4e1 for [UUM-58478](https://jira.unity3d.com/browse/UUM-58478)
NOTE: This fix was part of the following trunk fix: [32011](https://github.cds.internal.unity3d.com/unity/unity/pull/32011)

Small fix to ensure that player doesn't fail on error;
`Library\PackageCache\com.unity.render-pipelines.core@14.0.9\Runtime\XR\XRMirrorView.cs(3,19): error CS0234: The type or namespace name 'XR' does not exist in the namespace 'UnityEngine' (are you missing an assembly reference?)`

Bug: [UUM-58478](https://jira.unity3d.com/browse/UUM-58478)
Backport: [UUM-60124](https://jira.unity3d.com/browse/UUM-60124)