[SRPF] GUIView update in the Building time could cause a failing SRP creation
Initial issue was connected to the GRD (UUM-78811). I couldn't replicate the crash in the Building process locally by some reason but there was an another issue. Whenever the project got built it will stop rendering and spam Blitter issue (UUM-83608). 

It appeared because RenderPipeline tried to recreate after an exception but failed and never succeed. Initial exception that was appearing after the Build was 

`InsufficientExecutionStackException: Insufficient stack to continue executing the program safely. This can happen from having too many functions on the call stack or function on the stack using too much stack space.`

It's a bit long but here's the full stack:
```
InsufficientExecutionStackException: Insufficient stack to continue executing the program safely. This can happen from having too many functions on the call stack or function on the stack using too much stack space.
UnityEngine.ScriptableObject.CreateScriptableObjectInstanceFromType (System.Type type, System.Boolean applyDefaultsAndReset) <0x26e75c712f0 + 0x0005a> in <b513437b2c4c4d11b3e96dd48342b628>:0
UnityEngine.ScriptableObject.CreateInstance (System.Type type) (at C:/UnitySrc/unity_review/Runtime/Export/Scripting/ScriptableObject.bindings.cs:35)
UnityEngine.Rendering.VolumeStack.Reload (System.Type[] componentTypes) (at Library/PackageCache/com.unity.render-pipelines.core@637d86e54998/Runtime/Volume/VolumeStack.cs:50)
UnityEngine.Rendering.VolumeManager.CreateStack () (at Library/PackageCache/com.unity.render-pipelines.core@637d86e54998/Runtime/Volume/VolumeManager.cs:331)
UnityEngine.Rendering.HighDefinition.HDCamera.get_volumeStack () (at Library/PackageCache/com.unity.render-pipelines.high-definition@39aaede1aa83/Runtime/RenderPipeline/Camera/HDCamera.cs:133)
UnityEngine.Rendering.HighDefinition.HDCamera.UpdateVolumeAndPhysicalParameters () (at Library/PackageCache/com.unity.render-pipelines.high-definition@39aaede1aa83/Runtime/RenderPipeline/Camera/HDCamera.cs:2227)
UnityEngine.Rendering.HighDefinition.HDCamera.Update (UnityEngine.Rendering.HighDefinition.FrameSettings currentFrameSettings, UnityEngine.Rendering.HighDefinition.HDRenderPipeline hdrp, UnityEngine.Experimental.Rendering.XRPass xrPass, System.Boolean allocateHistoryBuffers) (at Library/PackageCache/com.unity.render-pipelines.high-definition@39aaede1aa83/Runtime/RenderPipeline/Camera/HDCamera.cs:1208)
UnityEngine.Rendering.HighDefinition.HDRenderPipeline.TryCalculateFrameParameters (UnityEngine.Camera camera, UnityEngine.Experimental.Rendering.XRPass xrPass, UnityEngine.Rendering.HighDefinition.HDAdditionalCameraData& additionalCameraData, UnityEngine.Rendering.HighDefinition.HDCamera& hdCamera, UnityEngine.Rendering.ScriptableCullingParameters& cullingParams) (at Library/PackageCache/com.unity.render-pipelines.high-definition@39aaede1aa83/Runtime/RenderPipeline/HDRenderPipeline.cs:2953)
UnityEngine.Rendering.HighDefinition.HDRenderPipeline.PrepareAndCullCamera (UnityEngine.Camera camera, UnityEngine.Experimental.Rendering.XRPass xrPass, System.Boolean cameraRequestedDynamicRes, System.Collections.Generic.List`1[T] renderRequests, UnityEngine.Rendering.ScriptableRenderContext renderContext, UnityEngine.Rendering.HighDefinition.HDRenderPipeline+RenderRequest& renderRequest, UnityEngine.CubemapFace cubemapFace) (at Library/PackageCache/com.unity.render-pipelines.high-definition@39aaede1aa83/Runtime/RenderPipeline/HDRenderPipeline.cs:1478)
UnityEngine.Rendering.HighDefinition.HDRenderPipeline.Render (UnityEngine.Rendering.ScriptableRenderContext renderContext, System.Collections.Generic.List`1[T] cameras) (at Library/PackageCache/com.unity.render-pipelines.high-definition@39aaede1aa83/Runtime/RenderPipeline/HDRenderPipeline.cs:2307)
UnityEngine.Rendering.RenderPipeline.InternalRender (UnityEngine.Rendering.ScriptableRenderContext context, System.Collections.Generic.List`1[T] cameras) (at C:/UnitySrc/unity_review/Runtime/Export/RenderPipeline/RenderPipeline.cs:52)
UnityEngine.Rendering.RenderPipelineManager.DoRenderLoop_Internal (UnityEngine.Rendering.RenderPipelineAsset pipelineAsset, System.IntPtr loopPtr, UnityEngine.Object renderRequest, Unity.Collections.LowLevel.Unsafe.AtomicSafetyHandle safety) (at C:/UnitySrc/unity_review/Runtime/Export/RenderPipeline/RenderPipelineManager.cs:152)
UnityEditor.Handles:Internal_DrawCameraWithGrid_Injected(IntPtr, DrawCameraMode, DrawGridParameters&, Boolean, Boolean)
UnityEditor.Handles:Internal_DrawCameraWithGrid(Camera, DrawCameraMode, DrawGridParameters&, Boolean, Boolean)
UnityEditor.Handles:DrawCameraImpl(Rect, Camera, DrawCameraMode, Boolean, DrawGridParameters, Boolean, Boolean, Boolean, GameObject[]) (at C:/UnitySrc/unity_review/Editor/Mono/Handles/Handles.cs:1583)
UnityEditor.Handles:DrawCameraStep1(Rect, Camera, DrawCameraMode, DrawGridParameters, Boolean, Boolean) (at C:/UnitySrc/unity_review/Editor/Mono/Handles/Handles.cs:1606)
UnityEditor.SceneView:DoDrawCamera(Rect, Rect, Boolean&) (at C:/UnitySrc/unity_review/Editor/Mono/SceneView/SceneView.cs:2284)
UnityEditor.SceneView:DoOnGUI() (at C:/UnitySrc/unity_review/Editor/Mono/SceneView/SceneView.cs:2613)
UnityEditor.SceneView:OnSceneGUI() (at C:/UnitySrc/unity_review/Editor/Mono/SceneView/SceneView.cs:2526)
UnityEngine.UIElements.IMGUIContainer:DoOnGUI(Event, Matrix4x4, Rect, Boolean, Rect, Action, Boolean) (at C:/UnitySrc/unity_review/Modules/UIElements/Core/IMGUIContainer.cs:403)
UnityEngine.UIElements.IMGUIContainer:HandleIMGUIEvent(Event, Matrix4x4, Rect, Action, Boolean) (at C:/UnitySrc/unity_review/Modules/UIElements/Core/IMGUIContainer.cs:718)
UnityEngine.UIElements.IMGUIContainer:DoIMGUIRepaint() (at C:/UnitySrc/unity_review/Modules/UIElements/Core/IMGUIContainer.cs:583)
UnityEngine.UIElements.UIR.RenderChainCommand:ExecuteNonDrawMesh(DrawParams, Single, Exception&) (at C:/UnitySrc/unity_review/Modules/UIElements/Core/Renderer/UIRenderer/UIRenderers.cs:128)
UnityEngine.UIElements.UIR.UIRenderDevice:EvaluateChain(RenderChainCommand, Material, Material, Texture, Texture, Single, Exception&) (at C:/UnitySrc/unity_review/Modules/UIElements/Core/Renderer/UIRenderer/UIRenderDevice.cs:990)
UnityEngine.UIElements.UIR.RenderChain:Render() (at C:/UnitySrc/unity_review/Modules/UIElements/Core/Renderer/UIRRenderChain.cs:541)
UnityEngine.UIElements.UIRRepaintUpdater:Render() (at C:/UnitySrc/unity_review/Modules/UIElements/Core/Renderer/UIRRepaintUpdater.cs:124)
UnityEngine.UIElements.BaseVisualElementPanel:Render() (at C:/UnitySrc/unity_review/Modules/UIElements/Core/Panel.cs:719)
UnityEngine.UIElements.Panel:Render() (at C:/UnitySrc/unity_review/Modules/UIElements/Core/Panel.cs:1378)
UnityEditor.UIElements.EditorPanel:Render() (at C:/UnitySrc/unity_review/Modules/UIElementsEditor/EditorPanel.cs:97)
UnityEngine.UIElements.UIElementsUtility:DoDispatch(BaseVisualElementPanel) (at C:/UnitySrc/unity_review/Modules/UIElements/Core/UIElementsUtility.cs:484)
UnityEngine.UIElements.UIElementsUtility:UnityEngine.UIElements.IUIElementsUtility.ProcessEvent(Int32, IntPtr, Boolean&) (at C:/UnitySrc/unity_review/Modules/UIElements/Core/UIElementsUtility.cs:232)
UnityEngine.UIElements.UIEventRegistration:ProcessEvent(Int32, IntPtr) (at C:/UnitySrc/unity_review/Modules/UIElements/Core/UIElementsUtility.cs:76)
UnityEngine.UIElements.<>c:<.cctor>b__1_2(Int32, IntPtr) (at C:/UnitySrc/unity_review/Modules/UIElements/Core/UIElementsUtility.cs:30)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&) (at C:/UnitySrc/unity_review/Modules/IMGUI/GUIUtility.cs:219)
UnityEditor.BuildPipeline:BuildPlayerInternalNoCheck_Injected(String[], ManagedSpanWrapper&, ManagedSpanWrapper&, BuildTargetGroup, BuildTarget, Int32, BuildOptions, String[], Boolean)
UnityEditor.BuildPipeline:BuildPlayerInternalNoCheck(String[], String, String, BuildTargetGroup, BuildTarget, Int32, BuildOptions, String[], Boolean)
UnityEditor.DefaultBuildMethods:BuildPlayer(BuildPlayerOptions) (at C:/UnitySrc/unity_review/Editor/Mono/BuildPlayerWindowBuildMethods.cs:169)
UnityEditor.BuildPlayerWindow:CallBuildMethods(Boolean, BuildOptions) (at C:/UnitySrc/unity_review/Editor/Mono/BuildPlayerWindowBuildMethods.cs:96)
UnityEditor.Build.Profile.BuildProfileModuleUtil:CallInternalBuildMethods(Boolean, BuildOptions) (at C:/UnitySrc/unity_review/Editor/Mono/BuildProfile/BuildProfileModuleUtil.cs:206)
UnityEditor.Build.Profile.BuildProfileWindow:OnBuildButtonClicked(BuildOptions) (at C:/UnitySrc/unity_review/Modules/BuildProfileEditor/BuildProfileWindow.cs:498)
UnityEditor.Build.Profile.BuildProfileWindow:<CreateBuildDropdownButton>b__47_0() (at C:/UnitySrc/unity_review/Modules/BuildProfileEditor/BuildProfileWindow.cs:606)
UnityEditor.GenericMenu:CatchMenu(Object, String[], Int32) (at C:/UnitySrc/unity_review/Editor/Mono/GUI/GenericMenu.cs:127)
```

By looking at this stack we can see that we have a UI update call that triggered in the middle of the Building process. By some reason I couldn't catch Native part of it this time. Usually it goes through GUIView update or through update of camera preview window.
 
As we had Domain Reload before because of the Build to execute Rendering correctly we have to create new Render Pipeline.
This will trigger re-creation of the Volume Stack for Default Volume, for SkyManager and for available cameras in the scene.
For this specific project it's 48 different ScriptableObjects that needs to be created. In some other tests it fails when starts creating for SkyManager. Here it's failing when Camera's ones are creating.

Here we see that it actually fails inside ScriptableObject.CreateInstance method. Usually it succeed here without any issues otherwise we would see that all the time. Changing callstack like moving things around sometimes fix this issue but it's quite unreliable.

To summarize we try to Render in the middle of the Building process. It's not clear why Mono is failing here. It could be that the context behave a bit differently in the Building process or it's occupied with some temp information from Building process. 

It seems there's no benefits to actually update GUIView at this point. Usually this call happens on the empty Scene that are temporary loaded and you will see just empty Skybox there.
This is how GUIVIew update looks when there's an exception
![image](https://media.github.cds.internal.unity3d.com/user/5932/files/ec6c3e5c-f056-4ffb-9c37-07533534e36b)

If there were no exception there will be empty Skybox instead of scene.
Kind of like this
![image](https://media.github.cds.internal.unity3d.com/user/5932/files/0a4e81a9-03d3-4dba-a63f-b12f914a0c95)

I checked 829763 case that was specified in the code and this PR doesn't affect it. It actually doesn't work though.