[22.2] Backport #24168 - Centralize GTF and UTF references for graphics test projects
Backport https://github.cds.internal.unity3d.com/unity/unity/pull/24168: Centralize UTF/GTF references to a single location instead of in the 25 project manifests.

Additionally fixes the VFX test projects that were broken by https://github.cds.internal.unity3d.com/unity/unity/pull/25743.
```
Script Compilation Problem at Tests\SRPTests\Packages\com.unity.testing.xr\Runtime\ConfigureMockHMD.csC:\build\output\unity\unity\Tests\SRPTests\Packages\com.unity.testing.xr\Runtime\ConfigureMockHMD.cs(14,94): error CS0234: The type or namespace name 'Graphics' does not exist in the namespace 'UnityEngine.TestTools' (are you missing an assembly reference?)
``` 
([link](https://unity-ci.cds.internal.unity3d.com/job/22871082))
We needed this backport before doing early cleaning.