Bump GTF for testing.urp-upgrade package
The URP Upgrade tests are failing with 
```
[02:26:44.855 Information] ***
Overall status: FAIL
Reason(s): One or more scripts have failed to compile.
Detail(s): Message: Library\PackageCache\com.unity.testframework.graphics@7.8.23-exp.2\Editor\SetupGraphicsTestCases.cs(30,42): error CS0117: 'TestRunnerApi' does not contai
[02:26:44.857 Information] n a definition for 'GetActiveRunGuids', File: Library\PackageCache\com.unity.testframework.graphics@7.8.23-exp.2\Editor\SetupGraphicsTestCases.cs, Line: 30
Message: Library\PackageCache\com.unity.testframework.graphics@7.8.23-exp.2\Editor\SetupGraphicsTestCases.cs(32,54): error CS0117: 'TestRunnerApi' does not contain a definition for 'GetExecutionSettings', File: Library\PackageCache\com.unity.testframework.graphics@7.8.23-exp.2\Editor\SetupGraphicsTestCases.cs, Line: 32
Message: Library\PackageCache\com.unity.testframework.graphics@7.8.23-exp.2\Editor\SetupGraphicsTestCases.cs(30,42): error CS0117: 'TestRunnerApi' does not contain a definition for 'GetActiveRunGuids', File: Library\PackageCache\com.unity.testframework.graphics@7.8.23-exp.2\Editor\SetupGraphicsTestCases.cs, Line: 30
Message: Library\PackageCache\com.unity.testframework.graphics@7.8.23-exp.2\Editor\SetupGraphicsTestCases.cs(32,54): error CS0117: 'TestRunnerApi' does not contain a definition for 'GetExecutionSettings', File: Library\PackageCache\com.unity.testframework.graphics@7.8.23-exp.2\Editor\SetupGraphicsTestCases.cs, Line: 32
```
This is because the project needs this fix from the graphics test framework (GTF): https://github.cds.internal.unity3d.com/unity/com.unity.testframework.graphics/pull/131/files and https://github.cds.internal.unity3d.com/unity/com.unity.testframework.graphics/pull/138

So this PR is bumping the dependency.