[URP/VFX] Fix XOne build error
`XRSystem.cs(38,22): error CS0414: The field 'XRSystem.s_OcclusionMeshScaling' is assigned but its value is never used`
Issue introduced at https://github.cds.internal.unity3d.com/unity/unity/pull/22068
This problem occurs because the VFX project are setup with compilation warning as error.