Remove com.unity.analytics from SRP_SmokeTest project
Removed com.unity.analytics from project manifest, which in the past has caused the following error to be printed. 

> error: No cloud project ID was found by the Analytics SDK. This means Analytics events will not be sent. Please make sure to link your cloud project in the Unity editor to fix this problem.

The error doesn't happen in trunk anymore, but better to get rid of the unnecessary package reference anyway.