[Backport][2022.3][VFX] Copy paste PointCache when the asset is missing raise exception and lose links
Jira: UUM-46548

Steps to reproduce:

1. Create new project and import visual effects graph package
2. Create new empty graph
3. Open attached project in another editor instance
4. Open "New VFX" effect from the attached project
5. In visual effects window, select all nodes and blocks and copy them
6. Return to the newly create project and paste them
7. Notice that node connections are lost, some nodes might not have been copied over and there's an exception in console
ArgumentException: Object of type 'UnityEngine.Object' cannot be converted to type 'UnityEditor.Experimental.VFX.Utility.PointCacheAsset'.

Expected result: All nodes and their connections are copied over to the new project

Note: the exception can also be reproduced by deleting point cache file that is used by a visual effect.

Reproduced with:
2021.3.29f1 using 12.1.12
2022.3.7f1 using 14.0.8
2023.1.9f1 using 15.0.6
2023.2.0b4 using 16.0.3