[VFX] Custom attribute and Custom HLSL compilation issues (independent)
### UUM-49725
How to reproduce:
- Create a new graph
- Duplicate attribute of Vector3 type
- In the Blackboard rename attribute to 'TEST' (looks like capitalization has an impact, it worked for me when it was named as 'test')
- Place it in the Output Context

Actual result: VFX is no longer rendered and errors are thrown to the console
![](https://jira.unity3d.com/secure/attachment/1269421/Screenshot%202023-09-21%20at%2010.37.12.png)

### UUM-49811
How to reproduce:
- Create a new graph and add it to the scene
- Add custom HLSL block to Update context
- Save graph
- Observe that vfx is no longer rendered and error is thrown to the console

Note: couldn't repro on 2023.3.0a3

> Unity cannot compile the VisualEffectAsset at path "Assets/TEST hlsl/Main Graph.vfx" because of the following exception:
> UnityEngine.UnassignedReferenceException: The variable m_ShaderFile of CustomHLSL has not been assigned.
> You probably need to assign the m_ShaderFile variable of the CustomHLSL script in the inspector. at UnityEngine.Object+MarshalledUnityObject.TryThrowEditorNullExceptionObject
>