[2021.3] Bump Graphics Test Framework dependency in SRP test projects
- Fixes this issue:
```
Details: Message: Library\PackageCache\com.unity.testframework.graphics@7.8.23-exp.2\Editor\SetupGraphicsTestCases.cs(30,42): error CS0117: 'TestRunnerApi' does not contain a definition for 'GetActiveRunGuids', File: Library\PackageCache\com.unity.testframework.graphics@7.8.23-exp.2\Editor\SetupGraphicsTestCases.cs, Line: 30
```
https://unity-ci.cds.internal.unity3d.com/job/19788226
by bumping the GTF version to 7.11.1-exp.1 (latest) in all the SRP test projects relying on it.

- Also removed some `package.lock.json` files, as was done in the original trunk PR. We don't need to version these files as they are regenerated when tests are run in the CI. And it's one less place to update when doing such modifications to the projects' dependencies.