[RPW] Fix error when selecting "Revert" under Volume Component context menu
When right-clicking on a Parameter inside a Volume Component and selecting "Revert Property Override", an error is triggered. This PR fixes that by adding the missing null check.

![image](https://media.github.cds.internal.unity3d.com/user/3380/files/7c97ab5e-f451-4994-a110-c59641e8ba2c)

```
ArgumentNullException: Value cannot be null.
Parameter name: source
System.Linq.Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable`1[T] source) (at <30a10d8f441b49b3bc2afc87180fc2ee>:0)
UnityEngine.Rendering.VolumeManager.OnVolumeComponentChanged (UnityEngine.Rendering.VolumeComponent component) (at ./Library/PackageCache/com.unity.render-pipelines.core@16.0.2/Runtime/Volume/VolumeManager.cs:298)
UnityEngine.Rendering.VolumeComponent+<>c.<TryGetRevertMethodForFieldName>b__20_0 (UnityEditor.SerializedProperty property) (at ./Library/PackageCache/com.unity.render-pipelines.core@16.0.2/Runtime/Volume/VolumeComponent.EditorOnly.cs:22)
UnityEditor.EditorGUI+<>c__DisplayClass297_3.<FillPropertyContextMenu>b__3 (System.Object o) (at <b958156a7a694bad8238d0453adee41e>:0)
UnityEditor.GenericMenu.CatchMenu (System.Object userData, System.String[] options, System.Int32 selected) (at <b958156a7a694bad8238d0453adee41e>:0)
```