[2022.1] Disable project updates for HDRP DXR
This is a backport of https://github.com/Unity-Technologies/Graphics/pull/7204.
It disables the project updates when this project is run in CI, to avoid issues caused by the implicit (and unintended) ads package bump:
```
##### Output
Library\PackageCache\com.unity.ads@4.0.1\Runtime\Advertisement\Platform\Editor\Placeholder.cs(83,47): error CS0619: 'ScreenOrientation.Landscape' is obsolete: 'Use LandscapeLeft instead (UnityUpgradable) -> LandscapeLeft'
```
More context in the [slack thread](https://unity.slack.com/archives/CFZERNTS7/p1663251411380989?thread_ts=1642096460.037000&cid=CFZERNTS7).