[URP] Fix build Vulkan/VR
Small compilation issue introduced at https://github.cds.internal.unity3d.com/unity/unity/pull/31962
It can be detected enabling warning as error
```
Script Compilation Problem at Packages\com.unity.render-pipelines.universal\Runtime\ShadowUtils.cs
C:\build\output\unity\unity\Packages\com.unity.render-pipelines.universal\Runtime\ShadowUtils.cs(574,13): error CS0162: Unreachable code detected
```